import type { NextPage } from 'next'
import Link from 'next/link'
import { Container, Header, List, ListItem } from './dashboard.style'
import Head from 'next/head'

const Dashboard: NextPage = () => {
  return (
    <>
      <Header>
        <h1>Fineasy</h1>
        <nav>
          <ul>
            <li>
              <Link href="#">
                <a>Dashboard</a>
              </Link>
            </li>
          </ul>
        </nav>
      </Header>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div>
          <List>
            <ListItem backgroundColor="income" >
              <h3>Income</h3>
              <span>R$ 10.000,00</span>
            </ListItem>
            <ListItem backgroundColor="outcome">
              <h3>Outcome</h3>
              <span>R$ 5.583,07</span>
            </ListItem>
            <ListItem backgroundColor="total">
              <h3>Total</h3>
              <span>R$ 3.000,00</span>
            </ListItem>
          </List>

          <section>
            <h1>Transactions</h1>
            <List type="summary">
              <ListItem  >
                <div>
                  <h4>Barzim</h4>
                  <span>20/02/2022</span>
                </div>
                <span>R$ 22,20</span>
              </ListItem>
              <ListItem>
                <div>
                  <h4>Futebol</h4>
                  <span>21/02/2022</span>
                </div>
                <span>R$ 30,20</span>
              </ListItem>
            </List>
          </section>
        </div>
      </Container>
    </>
  )
}

export default Dashboard
