import type { NextPage } from "next";
import { useQuery } from "react-query";
import Head from "next/head";
import Dashboard from "./dashboard";

const Home: NextPage = () => {
  const { data } = useQuery("transactions", async () => {
    const response = await fetch("http://localhost:3000/api/transactions");
    const result = await response.json();
    return result;
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard data={data?.transactions} />
    </>
  );
};

export default Home;
