import type { NextPage } from "next";
import Head from "next/head";
import { Header, List as ListComponent, Modal } from "@/components";
import { ITransactions } from "@/types/transactions";
import { Container, Fieldset, Input, Label, List, ListItem } from "./styles";

interface DashboardProps {
  data: ITransactions[];
}

const Dashboard: NextPage<DashboardProps> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <div>
          <ListComponent
            data={[
              <>
                <h3>Income</h3>
                <span>R$ 10.000,00</span>
              </>,
              <>
                <h3>Outcome</h3>
                <span>R$ 5.583,07</span>
              </>,
              <>
                <h3>Total</h3>
                <span>R$ 3.000,00</span>
              </>,
            ]}
          />
          <section>
            <h1>Transactions</h1>
            <List type="summary">
              {data?.map((transaction) => (
                <ListItem type="income" key={transaction.id}>
                  <div>
                    <h3>{transaction.title}</h3>
                    <small>{transaction.date}</small>
                  </div>
                  <span>{`R$ ${transaction.price}`}</span>
                </ListItem>
              ))}
            </List>
          </section>
        </div>
        <Modal show title="Add Transactions">
          <Fieldset>
            <Label htmlFor="name">Name</Label>
            <Input id="name" defaultValue="Pedro Duarte" />
          </Fieldset>
          <Fieldset>
            <Label htmlFor="username">Username</Label>
            <Input id="username" defaultValue="@peduarte" />
          </Fieldset>
        </Modal>
      </Container>
    </>
  );
};

export default Dashboard;
